### ISSUE TITLE
Could not install BotConnect.

### ISSUE THREAD

**Issue by Horizon2018** [nodebotrpa/connect#1]
Microsoft Windows [Version 10.0.19041.450]
(c) 2019 Microsoft Corporation. Tüm hakları saklıdır.

C:\PrgW\Icra>cd C:\Program Files\nodejs

C:\Program Files\nodejs>node ws-ssl.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'ws'
Require stack:
- C:\Program Files\nodejs\ws-ssl.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loade
:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\Program Files\nodejs\ws-ssl.js:64:19)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.j
0)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/module
in.js:71:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Program Files\\nodejs\\ws-ssl.js'←[39m ]
}

**Comment by burque505** [comment]
@Horizon2018, you can try the instructions for installation at [this link to nodebotrpa/editor](https://github.com/nodebotrpa/editor). You may want to install ws globally if it won't start after you follow the installation instructions.
`npm install -g ws`
You may have to follow the instructions for installing all automation modules.

**Comment by nodebotrpa** [comment]
Thanks @burque505 for your answer. @Horizon2018, ws installation instruction is also added.
